insert into club (name) values ('SV Unterneukirchen'),
('TuS Alztal Garching'), ('SV Mehring'), ('SV Wacker Burghausen'),
('DJK SG Ramsau'), ('TSV Neumarkt St. Veit'), ('TSV Taufkirchen'),
('ESV Wang'), ('TSV Buchbach'), ('EC Altötting'), ('EC Holzland-Arbing'),
('SV Gendorf Burgkirchen'), ('EC Ebing'), ('DJK-SV Emmerting'),
('SV St. Erasmus'), ('RfV Flossing'), ('EC Frauendorf'), ('TSV Gars am Inn'),
('ESV Grafengars'), ('ESV Grünbach'), ('FC Grünthal'), ('TSV Haag'),
('ESV Hackltal'), ('SV Haiming'), ('SV Halsbach'), ('SV Hirten'), ('STS Hörbering'),
('FC Maitenbeth'), ('TuS Mettenheim'), ('ESV Mittergars'), ('ESC Mößling'),
('SG Niederbergkirchen'), ('DJK Niedertaufkirchen'), ('SV Oberbergkirchen'),
('DJK SV Oberndorf'), ('TSV Obertaufkirchen'), ('TSV Obertaufkirchen'),
('FC Perach'), ('DJK-SV Pleiskirchen'), ('TSV Polling'), ('EV Pürten'),
('SC 66 Rechtmehring'), ('TSV Reischach'), ('SV Schönberg'), ('SV Schwindegg'),
('TSV Stammham'), ('SV Teising'), ('TuS Töging'), ('SV Tüßling'),
('ESV Waldkraiburg'), ('VfR Walkersaich'), ('TSV Winhöring')
